services:
  - type: web
    name: video-refs-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: APIFY_TOKEN
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: INSTAGRAM_COOKIES
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    disk:
      name: video-storage
      mountPath: /opt/render/project/videos
      sizeGB: 2