services:
  - type: web
    name: video-refs-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: APIFY_TOKEN
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000